export const VEHICLE_TRIMS = {
  "Acura": {
    "ILX": ["Base", "Premium", "A-Spec", "Technology"],
    "Integra": ["Base", "A-Spec", "A-Spec Technology", "Type S"],
    "MDX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
    "RDX": ["Base", "Technology", "A-Spec", "Advance"],
    "TLX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
    "TSX": ["Base", "Technology", "Special Edition"],
    "RSX": ["Base", "Type S"],
    "NSX": ["Base", "Type S"]
  },
  "Audi": {
    "A3": ["Premium", "Premium Plus", "Prestige"],
    "A3 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "A4": ["Premium", "Premium Plus", "Prestige"],
    "A4 allroad": ["Premium", "Premium Plus", "Prestige"],
    "A5": ["Premium", "Premium Plus", "Prestige"],
    "A5 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "A6": ["Premium", "Premium Plus", "Prestige"],
    "A6 allroad": ["Premium", "Premium Plus", "Prestige"],
    "A7": ["Premium", "Premium Plus", "Prestige"],
    "A8": ["Base", "L"],
    "A8 L": ["Base", "Sport"],
    "Q3": ["Premium", "Premium Plus", "Prestige"],
    "Q4 e-tron": ["Premium", "Premium Plus", "Prestige"],
    "Q5": ["Premium", "Premium Plus", "Prestige"],
    "Q5 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "Q7": ["Premium", "Premium Plus", "Prestige"],
    "Q8": ["Premium", "Premium Plus", "Prestige"],
    "Q8 e-tron": ["Premium", "Premium Plus", "Prestige"],
    "e-tron GT": ["Premium Plus", "Prestige"],
    "RS 3": ["Base"],
    "RS 5": ["Base"],
    "RS 6 Avant": ["Base"],
    "RS 7": ["Base"],
    "RS e-tron GT": ["Base"],
    "S3": ["Premium", "Premium Plus", "Prestige"],
    "S4": ["Premium", "Premium Plus", "Prestige"],
    "S5": ["Premium", "Premium Plus", "Prestige"],
    "S6": ["Premium", "Premium Plus", "Prestige"],
    "S7": ["Premium", "Premium Plus", "Prestige"],
    "SQ5": ["Premium", "Premium Plus", "Prestige"],
    "SQ7": ["Premium", "Premium Plus", "Prestige"],
    "SQ8": ["Premium", "Premium Plus", "Prestige"],
    "TT": ["Base", "S line"],
    "TT RS": ["Base"]
  },
  "BMW": {
    "228i": ["Base", "xDrive"],
    "230i": ["Base", "xDrive"],
    "M235i": ["xDrive"],
    "M240i": ["Base", "xDrive"],
    "320i": ["Base", "xDrive"],
    "328i": ["Base", "xDrive"],
    "330i": ["Base", "xDrive"],
    "330e": ["Base", "xDrive"],
    "335i": ["Base", "xDrive"],
    "340i": ["Base", "xDrive"],
    "M340i": ["Base", "xDrive"],
    "428i": ["Base", "xDrive"],
    "430i": ["Base", "xDrive"],
    "440i": ["Base", "xDrive"],
    "M440i": ["Base", "xDrive"],
    "525i": ["Base"],
    "528i": ["Base", "xDrive"],
    "530i": ["Base", "xDrive"],
    "530e": ["Base", "xDrive"],
    "535i": ["Base", "xDrive"],
    "540i": ["Base", "xDrive"],
    "M550i": ["xDrive"],
    "740i": ["Base", "xDrive"],
    "745e": ["xDrive"],
    "750i": ["xDrive"],
    "760i": ["xDrive"],
    "X1": ["sDrive28i", "xDrive28i"],
    "X2": ["sDrive28i", "xDrive28i", "M35i"],
    "X3": ["sDrive30i", "xDrive30i", "M40i"],
    "X4": ["xDrive30i", "M40i"],
    "X5": ["sDrive40i", "xDrive40i", "xDrive45e", "xDrive50e", "M50i"],
    "X6": ["xDrive40i", "M50i"],
    "X7": ["xDrive40i", "xDrive60i", "M60i"],
    "M3": ["Base", "Competition", "Competition xDrive"],
    "M4": ["Base", "Competition", "Competition xDrive"],
    "M5": ["Base", "Competition"],
    "M8": ["Base", "Competition"],
    "iX": ["xDrive40", "xDrive50", "M60"],
    "i4": ["eDrive35", "eDrive40", "xDrive40", "M50"],
    "i5": ["eDrive40", "xDrive40", "M60"],
    "i7": ["xDrive60", "M70"]
  },
  "Buick": {
    "Enclave": ["Preferred", "Essence", "Premium", "Avenir"],
    "Encore": ["Preferred", "Sport Touring", "Essence"],
    "Encore GX": ["Preferred", "Select", "Essence", "Avenir"],
    "Envision": ["Preferred", "Essence", "Avenir"],
    "LaCrosse": ["Preferred", "Essence", "Sport Touring", "Avenir"],
    "Regal": ["Preferred", "Essence", "Avenir", "GS"]
  },
  "Cadillac": {
    "CT4": ["Luxury", "Premium Luxury", "Sport", "V-Series", "V-Series Blackwing"],
    "CT5": ["Luxury", "Premium Luxury", "Sport", "V-Series", "V-Series Blackwing"],
    "Escalade": ["Luxury", "Premium Luxury", "Sport", "V-Series"],
    "XT4": ["Luxury", "Premium Luxury", "Sport"],
    "XT5": ["Luxury", "Premium Luxury", "Sport"],
    "XT6": ["Luxury", "Premium Luxury", "Sport"],
    "LYRIQ": ["Tech", "Luxury"],
    "CTS": ["Base", "Luxury", "Premium Luxury", "V-Sport", "V"],
    "ATS": ["Base", "Luxury", "Premium", "Performance", "V"]
  },
  "Chevrolet": {
    "Blazer": ["LT", "RS", "Premier"],
    "Camaro": ["LS", "LT", "LT1", "SS", "ZL1"],
    "Colorado": ["WT", "LT", "Z71", "Trail Boss", "ZR2"],
    "Corvette": ["1LT", "2LT", "3LT", "1LZ", "2LZ", "3LZ"],
    "Equinox": ["LS", "LT", "RS", "Premier", "Activ"],
    "Malibu": ["LS", "RS", "LT", "Premier"],
    "Silverado 1500": ["WT", "Custom", "Custom Trail Boss", "LT", "RST", "LT Trail Boss", "LTZ", "High Country"],
    "Silverado 2500HD": ["WT", "Custom", "LT", "LTZ", "High Country"],
    "Suburban": ["LS", "RST", "LT", "Z71", "Premier", "High Country"],
    "Tahoe": ["LS", "RST", "LT", "Z71", "Premier", "High Country"],
    "Traverse": ["LS", "LT", "RS", "Premier", "High Country"],
    "Trax": ["LS", "LT", "RS", "Activ"],
    "Bolt EV": ["1LT", "2LT"],
    "Bolt EUV": ["LT", "Premier"],
    "Trailblazer": ["LS", "LT", "Activ", "RS"]
  },
  "Chrysler": {
    "300": ["Touring", "Touring L", "S", "C"],
    "Pacifica": ["Touring", "Touring L", "Limited", "Pinnacle"],
    "Voyager": ["LX", "LXi"]
  },
  "Dodge": {
    "Challenger": ["SXT", "GT", "R/T", "R/T Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye"],
    "Charger": ["SXT", "GT", "R/T", "Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye"],
    "Durango": ["SXT", "GT", "Citadel", "R/T", "SRT Hellcat"],
    "Hornet": ["GT", "R/T", "R/T Plus"],
    "Ram 1500": ["Tradesman", "Big Horn", "Laramie", "Rebel", "Limited", "TRX"],
    "Ram 2500": ["Tradesman", "Big Horn", "Laramie", "Power Wagon", "Limited", "Limited Longhorn"]
  },
  "Ford": {
    "Bronco": ["Base", "Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Raptor"],
    "Bronco Sport": ["Base", "Big Bend", "Outer Banks", "Badlands"],
    "Edge": ["SE", "SEL", "ST-Line", "ST", "Titanium"],
    "Escape": ["Base", "Active", "ST-Line", "ST-Line Select", "Platinum"],
    "Expedition": ["XLT", "Limited", "Timberline", "King Ranch", "Platinum"],
    "Explorer": ["Base", "XLT", "ST-Line", "Limited", "Timberline", "ST", "Platinum"],
    "F-150": ["XL", "STX", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor", "Raptor"],
    "F-250": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited"],
    "Maverick": ["XL", "XLT", "Lariat", "Tremor"],
    "Mustang": ["EcoBoost", "EcoBoost Premium", "GT", "GT Premium", "Dark Horse", "Mach 1"],
    "Mustang Mach-E": ["Select", "Premium", "California Route 1", "GT"],
    "Ranger": ["XL", "XLT", "Lariat", "Raptor"],
    "Lightning": ["Pro", "XLT", "Lariat", "Platinum"],
    "Transit": ["Base", "XL", "XLT"]
  },
  "Genesis": {
    "G70": ["2.0T Standard", "2.0T Advanced", "3.3T Sport Advanced", "3.3T Sport Prestige"],
    "G80": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "Sport"],
    "G90": ["3.5T Standard", "3.5T Prestige", "e3.5T"],
    "GV70": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "3.5T Sport Advanced", "3.5T Sport Prestige"],
    "GV80": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "3.5T Advanced", "3.5T Prestige"]
  },
  "GMC": {
    "Acadia": ["SLE", "SLT", "AT4", "Denali"],
    "Canyon": ["Elevation", "AT4", "AT4X", "Denali"],
    "Sierra 1500": ["Pro", "SLE", "Elevation", "SLT", "AT4", "AT4X", "Denali", "Denali Ultimate"],
    "Sierra 2500HD": ["Pro", "SLE", "SLT", "AT4", "AT4X", "Denali", "Denali Ultimate"],
    "Terrain": ["SLE", "SLT", "AT4", "Denali"],
    "Yukon": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Yukon XL": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Hummer EV": ["EV2", "EV2X", "EV3X", "Edition 1"]
  },
  "Honda": {
    "Accord": ["LX", "EX", "EX-L", "Sport", "Sport SE", "Touring"],
    "Civic": ["LX", "Sport", "EX", "EX-L", "Touring", "Si", "Type R"],
    "CR-V": ["LX", "EX", "EX-L", "Sport", "Sport Touring"],
    "HR-V": ["LX", "Sport", "EX-L"],
    "Odyssey": ["LX", "EX", "EX-L", "Touring", "Elite"],
    "Passport": ["EX-L", "Sport", "TrailSport", "Touring", "Elite"],
    "Pilot": ["LX", "EX", "EX-L", "Sport", "TrailSport", "Touring", "Elite"],
    "Ridgeline": ["Sport", "RTL", "RTL-E", "TrailSport", "Black Edition"],
    "Fit": ["LX", "Sport", "EX", "EX-L"],
    "Prologue": ["EX", "Touring"]
  },
  "Hyundai": {
    "Elantra": ["SE", "SEL", "Limited", "N Line", "N"],
    "Ioniq 5": ["SE Standard Range", "SE", "SEL", "Limited"],
    "Ioniq 6": ["SE Standard Range", "SE", "SEL", "Limited"],
    "Kona": ["SE", "SEL", "N Line", "Limited", "N"],
    "Palisade": ["SE", "SEL", "XRT", "Limited", "Calligraphy"],
    "Santa Cruz": ["SE", "SEL", "SEL Activity", "Limited"],
    "Santa Fe": ["SE", "SEL", "XRT", "Limited", "Calligraphy"],
    "Sonata": ["SE", "SEL", "SEL Plus", "Limited", "N Line"],
    "Tucson": ["SE", "SEL", "XRT", "N Line", "Limited"],
    "Venue": ["SE", "SEL"]
  },
  "Infiniti": {
    "Q50": ["Pure", "Luxe", "Sensory", "Red Sport 400"],
    "Q60": ["Pure", "Luxe", "Red Sport 400"],
    "QX50": ["Pure", "Luxe", "Essential", "Sensory", "Autograph"],
    "QX55": ["Luxe", "Essential", "Sensory"],
    "QX60": ["Pure", "Luxe", "Sensory", "Autograph"],
    "QX80": ["Luxe", "Sensory", "Autograph"]
  },
  "Jeep": {
    "Cherokee": ["Latitude", "Latitude Lux", "Altitude", "Limited", "Trailhawk"],
    "Compass": ["Sport", "Latitude", "Altitude", "Limited", "Trailhawk"],
    "Gladiator": ["Sport", "Willys", "Overland", "Rubicon", "Mojave"],
    "Grand Cherokee": ["Laredo", "Altitude", "Limited", "Overland", "Trailhawk", "Summit", "Summit Reserve"],
    "Grand Cherokee L": ["Laredo", "Altitude", "Limited", "Overland", "Summit", "Summit Reserve"],
    "Renegade": ["Sport", "Latitude", "Altitude", "Limited", "Trailhawk"],
    "Wagoneer": ["Series I", "Series II", "Series III"],
    "Wrangler": ["Sport", "Sport S", "Willys", "Sahara", "Rubicon"]
  },
  "Kia": {
    "EV6": ["Light", "Wind", "GT-Line", "GT"],
    "EV9": ["Light", "Wind", "GT-Line"],
    "Forte": ["LXS", "GT-Line", "GT"],
    "K5": ["LXS", "GT-Line", "EX", "GT"],
    "Seltos": ["LX", "S", "EX", "SX", "SX Turbo"],
    "Sorento": ["LX", "S", "EX", "SX", "SX Prestige", "X-Line", "X-Pro"],
    "Soul": ["LX", "S", "EX", "Turbo"],
    "Sportage": ["LX", "EX", "X-Line", "SX", "SX Prestige", "X-Pro", "X-Pro Prestige"],
    "Telluride": ["LX", "S", "EX", "SX", "SX Prestige", "X-Line", "X-Pro"],
    "Carnival": ["LX", "EX", "SX", "SX Prestige"]
  },
  "Lexus": {
    "ES 250": ["Base", "Luxury", "Ultra Luxury"],
    "ES 300h": ["Base", "Luxury", "Ultra Luxury"],
    "ES 350": ["Base", "Luxury", "F Sport", "Ultra Luxury"],
    "GS 300": ["Base", "F Sport"],
    "GS 350": ["Base", "F Sport"],
    "GS 430": ["Base"],
    "GS 450h": ["Base", "F Sport"],
    "GS 460": ["Base"],
    "GS F": ["Base"],
    "GX 460": ["Base", "Luxury", "Premium"],
    "GX 470": ["Base"],
    "GX 550": ["Premium", "Premium Plus", "Luxury", "Overtrail", "Overtrail+"],
    "IS 200t": ["Base", "F Sport"],
    "IS 250": ["Base", "F Sport"],
    "IS 300": ["Base", "F Sport"],
    "IS 350": ["Base", "F Sport"],
    "IS 500": ["F Sport Performance", "F Sport Performance Premium"],
    "IS F": ["Base"],
    "LC 500": ["Base", "Touring", "Inspiration Series"],
    "LC 500h": ["Base", "Touring"],
    "LS 400": ["Base"],
    "LS 430": ["Base"],
    "LS 460": ["Base", "L"],
    "LS 500": ["Base", "F Sport", "Luxury"],
    "LS 500h": ["Base", "F Sport", "Luxury"],
    "LS 600h": ["Base", "L"],
    "LX 470": ["Base"],
    "LX 570": ["Base"],
    "LX 600": ["Base", "Premium", "Luxury", "F Sport", "Ultra Luxury"],
    "NX 200t": ["Base", "F Sport"],
    "NX 250": ["Base", "Premium", "Luxury"],
    "NX 300": ["Base", "F Sport", "Luxury"],
    "NX 300h": ["Base", "Luxury"],
    "NX 350": ["F Sport"],
    "NX 350h": ["Base", "Premium", "Luxury", "F Sport"],
    "NX 450h+": ["Base", "Premium", "Luxury", "F Sport"],
    "RC 300": ["Base", "F Sport"],
    "RC 350": ["Base", "F Sport"],
    "RC F": ["Base", "Fuji Speedway Edition"],
    "RX 300": ["Base"],
    "RX 330": ["Base"],
    "RX 350": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 350h": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 450h": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 450h+": ["Base", "Premium", "Luxury"],
    "RX 500h": ["F Sport Performance"],
    "TX 350": ["Base", "Premium", "Luxury"],
    "TX 500h": ["F Sport", "Premium", "Luxury"],
    "TX 550h+": ["Base", "Premium", "Luxury"],
    "UX 200": ["Base", "Premium", "Luxury", "F Sport"],
    "UX 250h": ["Base", "Premium", "Luxury", "F Sport"],
    "RZ 300e": ["Base", "Premium"],
    "RZ 450e": ["Base", "Premium"]
  },
  "Lincoln": {
    "Aviator": ["Standard", "Reserve"],
    "Corsair": ["Standard", "Reserve"],
    "Nautilus": ["Standard", "Reserve"],
    "Navigator": ["Standard", "Reserve", "Black Label"]
  },
  "Mazda": {
    "CX-5": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "S Premium Plus", "Turbo"],
    "CX-30": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "Turbo", "Turbo Premium Plus"],
    "CX-50": ["S", "S Select", "S Preferred", "S Preferred Plus", "S Premium", "S Premium Plus", "Turbo", "Turbo Premium Plus", "Turbo Meridian"],
    "CX-70": ["S Premium", "S Premium Plus", "Turbo Premium", "Turbo Premium Plus"],
    "CX-90": ["S", "S Select", "S Preferred", "S Preferred Plus", "S Premium", "S Premium Plus", "Turbo S", "Turbo S Premium", "Turbo S Premium Plus"],
    "Mazda3": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "Turbo", "Turbo Premium Plus"],
    "MX-5 Miata": ["Sport", "Club", "Grand Touring"],
    "CX-9": ["Sport", "Touring", "Carbon Edition", "Grand Touring", "Signature"]
  },
  "Mercedes-Benz": {
    "A 220": ["Base", "AMG Line"],
    "C 300": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "C 43 AMG": ["Base"],
    "C 63 AMG": ["Base", "S"],
    "CLA 250": ["Base", "AMG Line"],
    "CLE 300": ["Base", "AMG Line"],
    "CLE 450": ["Base", "AMG Line"],
    "E 300": ["Base", "Luxury", "Sport"],
    "E 350": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "E 450": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "E 53 AMG": ["Base"],
    "E 63 AMG": ["Base", "S"],
    "S 500": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "S 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "S 63 AMG": ["Base"],
    "GLA 250": ["Base", "AMG Line"],
    "GLB 250": ["Base", "AMG Line"],
    "GLC 300": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLC 43 AMG": ["Base"],
    "GLC 63 AMG": ["Base", "S"],
    "GLE 350": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLE 450": ["Base", "AMG Line"],
    "GLE 53 AMG": ["Base"],
    "GLE 63 AMG": ["Base", "S"],
    "GLS 450": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLS 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLS 63 AMG": ["Base"],
    "G 550": ["Base", "AMG Line"],
    "G 63 AMG": ["Base"],
    "EQS 450+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQS 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQE 350+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "AMG GT": ["Base", "43", "53", "55", "63"],
    "AMG GT 63": ["Base", "S"]
  },
  "Nissan": {
    "Altima": ["S", "SV", "SR", "SL", "Platinum"],
    "Armada": ["S", "SV", "SL", "Platinum", "Midnight Edition"],
    "Frontier": ["S", "SV", "Pro-X", "Pro-4X"],
    "Kicks": ["S", "SV", "SR"],
    "Leaf": ["S", "SV", "SV Plus", "SL Plus"],
    "Maxima": ["SV", "SR", "Platinum"],
    "Murano": ["S", "SV", "SL", "Platinum"],
    "Pathfinder": ["S", "SV", "SL", "Rock Creek", "Platinum"],
    "Rogue": ["S", "SV", "SL", "Platinum"],
    "Sentra": ["S", "SV", "SR"],
    "Titan": ["S", "SV", "Pro-4X", "SL", "Platinum Reserve"],
    "Versa": ["S", "SV", "SR"],
    "Z": ["Sport", "Performance"],
    "Ariya": ["Engage", "Venture+", "Evolve+", "Empower+", "Platinum+"]
  },
  "Porsche": {
    "911": ["Carrera", "Carrera S", "Carrera T", "Carrera GTS", "Turbo", "Turbo S", "GT3", "GT3 RS"],
    "Cayenne": ["Base", "E-Hybrid", "S", "GTS", "Turbo", "Turbo GT"],
    "Macan": ["Base", "S", "GTS", "T", "Turbo"],
    "Panamera": ["Base", "4", "4S", "GTS", "4S E-Hybrid", "Turbo", "Turbo S"],
    "Taycan": ["Base", "4S", "GTS", "Turbo", "Turbo S"],
    "718 Boxster": ["Base", "T", "S", "GTS 4.0", "Spyder"],
    "718 Cayman": ["Base", "T", "S", "GTS 4.0", "GT4", "GT4 RS"]
  },
  "Ram": {
    "1500": ["Tradesman", "Big Horn", "Laramie", "Rebel", "Limited", "Limited Longhorn", "TRX"],
    "2500": ["Tradesman", "Big Horn", "Laramie", "Power Wagon", "Limited", "Limited Longhorn"],
    "3500": ["Tradesman", "Big Horn", "Laramie", "Limited", "Limited Longhorn"],
    "ProMaster": ["1500 Low Roof", "1500 High Roof", "2500 High Roof", "3500 High Roof"]
  },
  "Subaru": {
    "Ascent": ["Base", "Premium", "Onyx Edition", "Limited", "Touring"],
    "Crosstrek": ["Base", "Premium", "Sport", "Limited"],
    "Forester": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Impreza": ["Base", "Premium", "Sport", "Limited"],
    "Legacy": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Outback": ["Base", "Premium", "Onyx Edition", "Limited", "Touring", "Wilderness", "Onyx Edition XT", "Limited XT", "Touring XT"],
    "Solterra": ["Premium", "Limited", "Touring"],
    "WRX": ["Base", "Premium", "Limited", "GT"],
    "BRZ": ["Premium", "Limited"]
  },
  "Tesla": {
    "Model 3": ["Base", "Long Range", "Performance"],
    "Model S": ["Base", "Plaid"],
    "Model X": ["Base", "Plaid"],
    "Model Y": ["Base", "Long Range", "Performance"],
    "Cybertruck": ["Rear-Wheel Drive", "All-Wheel Drive", "Cyberbeast", "Foundation Series"]
  },
  "Toyota": {
    "4Runner": ["SR5", "SR5 Premium", "TRD Sport", "TRD Off-Road", "TRD Off-Road Premium", "Limited", "TRD Pro"],
    "86/GR86": ["Base", "Premium"],
    "Camry": ["LE", "SE", "XLE", "XSE", "TRD"],
    "Corolla": ["L", "LE", "SE", "XLE", "XSE"],
    "Corolla Cross": ["L", "LE", "XLE", "SE"],
    "Grand Highlander": ["LE", "XLE", "Limited", "Platinum"],
    "Highlander": ["L", "LE", "XLE", "XSE", "Limited", "Platinum"],
    "Land Cruiser": ["Base", "1958", "First Edition"],
    "Prius": ["LE", "XLE", "Limited", "Prime SE", "Prime XSE"],
    "RAV4": ["LE", "XLE", "XLE Premium", "SE", "XSE", "Adventure", "TRD Off-Road", "Limited", "Prime SE", "Prime XSE"],
    "Sequoia": ["SR5", "Limited", "Platinum", "TRD Pro", "Capstone"],
    "Sienna": ["LE", "XLE", "XSE", "Limited", "Platinum"],
    "Tacoma": ["SR", "SR5", "TRD Sport", "TRD Off-Road", "Limited", "TRD Pro", "Trailhunter"],
    "Tundra": ["SR", "SR5", "Limited", "Platinum", "1794 Edition", "TRD Pro", "Capstone"],
    "Venza": ["LE", "XLE", "Limited"],
    "bZ4X": ["XLE", "Limited"],
    "Crown": ["XLE", "Limited", "Platinum"],
    "GR Corolla": ["Core", "Circuit Edition", "Morizo Edition", "Premium"],
    "Supra": ["2.0", "3.0", "3.0 Premium", "A91 Edition"]
  },
  "Volkswagen": {
    "Atlas": ["S", "SE", "SEL", "SEL Premium"],
    "Atlas Cross Sport": ["S", "SE", "SE Technology", "SEL", "SEL Premium"],
    "Golf": ["S", "SE"],
    "Golf GTI": ["S", "SE", "Autobahn"],
    "Golf R": ["Base"],
    "ID.4": ["Standard", "S", "S Plus", "Pro", "Pro S", "Pro S Plus"],
    "ID.Buzz": ["Pro S", "Pro S Plus"],
    "Jetta": ["S", "Sport", "SE", "SEL"],
    "Taos": ["S", "SE", "SEL"],
    "Tiguan": ["S", "SE", "SE R-Line", "SEL", "SEL R-Line"],
    "Arteon": ["SE", "SE R-Line", "SEL R-Line", "SEL Premium R-Line"]
  },
  "Volvo": {
    "S60": ["Core", "Plus", "Ultimate"],
    "S90": ["Core", "Plus", "Ultimate"],
    "V60": ["Core", "Plus", "Ultimate"],
    "V90": ["Core", "Plus", "Ultimate"],
    "XC40": ["Core", "Plus", "Ultimate"],
    "XC60": ["Core", "Plus", "Ultimate"],
    "XC90": ["Core", "Plus", "Ultimate"],
    "C40 Recharge": ["Core", "Plus", "Ultimate"],
    "EX30": ["Core", "Plus", "Ultra"],
    "EX90": ["Core", "Plus", "Ultra"]
  }
};
