export const VEHICLE_TRIMS = {
  "Acura": {
    "ILX": ["Base", "Premium", "A-Spec", "Technology"],
    "Integra": ["Base", "A-Spec", "A-Spec Technology", "Type S"],
    "MDX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
    "RDX": ["Base", "Technology", "A-Spec", "Advance"],
    "TLX": ["Base", "Technology", "A-Spec", "Advance", "Type S", "Type S Advance"],
    "TSX": ["Base", "Technology", "Special Edition"],
    "RSX": ["Base", "Type S"],
    "NSX": ["Base", "Type S"],
    "RL": ["Base", "Technology"],
    "RLX": ["Base", "Technology", "Sport Hybrid", "Advance"],
    "TL": ["Base", "Technology", "SH-AWD", "Advance"],
    "CL": ["Base", "Type S", "Premium"],
    "ZDX": ["Base", "Technology", "Advance"]
  },
  "Audi": {
    "A3": ["Premium", "Premium Plus", "Prestige"],
    "A3 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "A4": ["Premium", "Premium Plus", "Prestige"],
    "A4 allroad": ["Premium", "Premium Plus", "Prestige"],
    "A5": ["Premium", "Premium Plus", "Prestige"],
    "A5 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "A6": ["Premium", "Premium Plus", "Prestige"],
    "A6 allroad": ["Premium", "Premium Plus", "Prestige"],
    "A7": ["Premium", "Premium Plus", "Prestige"],
    "A8": ["Base", "L"],
    "A8 L": ["Base", "Sport"],
    "Q3": ["Premium", "Premium Plus", "Prestige"],
    "Q4 e-tron": ["Premium", "Premium Plus", "Prestige"],
    "Q5": ["Premium", "Premium Plus", "Prestige"],
    "Q5 Sportback": ["Premium", "Premium Plus", "Prestige"],
    "Q7": ["Premium", "Premium Plus", "Prestige"],
    "Q8": ["Premium", "Premium Plus", "Prestige"],
    "Q8 e-tron": ["Premium", "Premium Plus", "Prestige"],
    "e-tron GT": ["Premium Plus", "Prestige"],
    "RS 3": ["Base"],
    "RS 5": ["Base"],
    "RS 6 Avant": ["Base"],
    "RS 7": ["Base"],
    "RS e-tron GT": ["Base"],
    "S3": ["Premium", "Premium Plus", "Prestige"],
    "S4": ["Premium", "Premium Plus", "Prestige"],
    "S5": ["Premium", "Premium Plus", "Prestige"],
    "S6": ["Premium", "Premium Plus", "Prestige"],
    "S7": ["Premium", "Premium Plus", "Prestige"],
    "SQ5": ["Premium", "Premium Plus", "Prestige"],
    "SQ7": ["Premium", "Premium Plus", "Prestige"],
    "SQ8": ["Premium", "Premium Plus", "Prestige"],
    "TT": ["Base", "S line"],
    "TT RS": ["Base"],
    "R8": ["V10", "V10 Plus", "V10 Performance", "V10 Spyder"]
  },
  "BMW": {
    "228i": ["Base", "xDrive"],
    "230i": ["Base", "xDrive"],
    "M235i": ["xDrive"],
    "M240i": ["Base", "xDrive"],
    "320i": ["Base", "xDrive"],
    "328i": ["Base", "xDrive"],
    "330i": ["Base", "xDrive"],
    "330e": ["Base", "xDrive"],
    "335i": ["Base", "xDrive"],
    "340i": ["Base", "xDrive"],
    "M340i": ["Base", "xDrive"],
    "428i": ["Base", "xDrive"],
    "430i": ["Base", "xDrive"],
    "440i": ["Base", "xDrive"],
    "M440i": ["Base", "xDrive"],
    "525i": ["Base"],
    "528i": ["Base", "xDrive"],
    "530i": ["Base", "xDrive"],
    "530e": ["Base", "xDrive"],
    "535i": ["Base", "xDrive"],
    "540i": ["Base", "xDrive"],
    "M550i": ["xDrive"],
    "740i": ["Base", "xDrive"],
    "745e": ["xDrive"],
    "750i": ["xDrive"],
    "760i": ["xDrive"],
    "X1": ["sDrive28i", "xDrive28i"],
    "X2": ["sDrive28i", "xDrive28i", "M35i"],
    "X3": ["sDrive30i", "xDrive30i", "M40i"],
    "X4": ["xDrive30i", "M40i"],
    "X5": ["sDrive40i", "xDrive40i", "xDrive45e", "xDrive50e", "M50i"],
    "X6": ["xDrive40i", "M50i"],
    "X7": ["xDrive40i", "xDrive60i", "M60i"],
    "M3": ["Base", "Competition", "Competition xDrive"],
    "M4": ["Base", "Competition", "Competition xDrive"],
    "M5": ["Base", "Competition"],
    "M8": ["Base", "Competition"],
    "iX": ["xDrive40", "xDrive50", "M60"],
    "i4": ["eDrive35", "eDrive40", "xDrive40", "M50"],
    "i5": ["eDrive40", "xDrive40", "M60"],
    "i7": ["xDrive60", "M70"],
    "Z4": ["sDrive30i", "M40i"],
    "i3": ["Base", "s", "Range Extender"],
    "i8": ["Base", "Roadster"]
  },
  "Buick": {
    "Enclave": ["Preferred", "Essence", "Premium", "Avenir"],
    "Encore": ["Preferred", "Sport Touring", "Essence"],
    "Encore GX": ["Preferred", "Select", "Essence", "Avenir"],
    "Envision": ["Preferred", "Essence", "Avenir"],
    "LaCrosse": ["Preferred", "Essence", "Sport Touring", "Avenir"],
    "Regal": ["Preferred", "Essence", "Avenir", "GS"],
    "Regal Sportback": ["Preferred", "Essence", "Avenir", "GS"],
    "Regal TourX": ["Preferred", "Essence", "Avenir"],
    "Verano": ["Base", "Convenience", "Leather", "Premium Turbo"],
    "Cascada": ["Base", "Sport Touring", "Premium"],
    "LeSabre": ["Custom", "Limited"],
    "Lucerne": ["CX", "CXL", "CXS", "Super"],
    "Rendezvous": ["CX", "CXL", "Ultra"],
    "Terraza": ["CX", "CXL"],
    "Century": ["Custom", "Limited"],
    "Park Avenue": ["Base", "Ultra"],
    "Rainier": ["CXL", "CXL Plus"],
    "Envista": ["Preferred", "Sport Touring", "Avenir"]
  },
  "Cadillac": {
    "CT4": ["Luxury", "Premium Luxury", "Sport", "V-Series", "V-Series Blackwing"],
    "CT5": ["Luxury", "Premium Luxury", "Sport", "V-Series", "V-Series Blackwing"],
    "Escalade": ["Luxury", "Premium Luxury", "Sport", "V-Series"],
    "Escalade ESV": ["Luxury", "Premium Luxury", "Sport"],
    "XT4": ["Luxury", "Premium Luxury", "Sport"],
    "XT5": ["Luxury", "Premium Luxury", "Sport"],
    "XT6": ["Luxury", "Premium Luxury", "Sport"],
    "LYRIQ": ["Tech", "Luxury"],
    "CTS": ["Base", "Luxury", "Premium Luxury", "V-Sport", "V"],
    "ATS": ["Base", "Luxury", "Premium", "Performance", "V"],
    "XTS": ["Base", "Luxury", "Premium", "Platinum", "V-Sport"],
    "CT6": ["Luxury", "Premium Luxury", "Sport", "Platinum", "V"],
    "SRX": ["Base", "Luxury", "Performance", "Premium"],
    "STS": ["V6", "V8"],
    "DTS": ["Base", "Luxury", "Performance", "Platinum"],
    "ELR": ["Base"],
    "Escalade EXT": ["Base", "Luxury", "Premium"],
    "CELESTIQ": ["Base"]
  },
  "Chevrolet": {
    "Blazer": ["LT", "RS", "Premier"],
    "Blazer EV": ["1LT", "2LT", "RS", "SS"],
    "Camaro": ["LS", "LT", "LT1", "SS", "ZL1"],
    "Colorado": ["WT", "LT", "Z71", "Trail Boss", "ZR2"],
    "Corvette": ["1LT", "2LT", "3LT", "1LZ", "2LZ", "3LZ"],
    "Equinox": ["LS", "LT", "RS", "Premier", "Activ"],
    "Equinox EV": ["1LT", "2LT", "2RS", "3RS"],
    "Malibu": ["LS", "RS", "LT", "Premier"],
    "Silverado 1500": ["WT", "Custom", "Custom Trail Boss", "LT", "RST", "LT Trail Boss", "LTZ", "High Country"],
    "Silverado 2500HD": ["WT", "Custom", "LT", "LTZ", "High Country"],
    "Silverado 3500HD": ["WT", "Custom", "LT", "LTZ", "High Country"],
    "Silverado EV": ["WT", "RST", "Trail Boss"],
    "Suburban": ["LS", "RST", "LT", "Z71", "Premier", "High Country"],
    "Tahoe": ["LS", "RST", "LT", "Z71", "Premier", "High Country"],
    "Traverse": ["LS", "LT", "RS", "Premier", "High Country"],
    "Trax": ["LS", "LT", "RS", "Activ"],
    "Bolt EV": ["1LT", "2LT"],
    "Bolt EUV": ["LT", "Premier"],
    "Trailblazer": ["LS", "LT", "Activ", "RS"],
    "Impala": ["LS", "LT", "Premier", "LTZ"],
    "Cruze": ["L", "LS", "LT", "Premier", "Diesel"],
    "Sonic": ["LS", "LT", "LTZ", "RS"],
    "Spark": ["LS", "LT", "1LT", "2LT", "ACTIV"],
    "Cobalt": ["LS", "LT", "LTZ", "SS"],
    "Aveo": ["LS", "LT"],
    "SS": ["Base"],
    "Monte Carlo": ["LS", "LT", "LTZ", "SS"],
    "HHR": ["LS", "LT", "LTZ", "SS"],
    "City Express": ["LS", "LT"],
    "Express": ["1500 LS", "2500 LS", "3500 LS", "LT"],
    "Captiva": ["LS", "LT", "Sport"],
    "Orlando": ["LS", "LT"],
    "Volt": ["LT", "Premier"],
    "Uplander": ["LS", "LT", "LTZ"]
  },
  "Chrysler": {
    "300": ["Touring", "Touring L", "S", "C"],
    "Pacifica": ["Touring", "Touring L", "Limited", "Pinnacle"],
    "Voyager": ["LX", "LXi"],
    "200": ["LX", "Limited", "S", "C"],
    "Town & Country": ["Touring", "Touring L", "Limited", "S"],
    "PT Cruiser": ["Base", "Touring", "Limited", "GT"],
    "Sebring": ["LX", "Touring", "Limited"],
    "Aspen": ["Limited", "Limited HEV"],
    "Crossfire": ["Base", "Limited", "SRT-6"]
  },
  "Dodge": {
    "Challenger": ["SXT", "GT", "R/T", "R/T Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye", "SRT Demon"],
    "Charger": ["SXT", "GT", "R/T", "Scat Pack", "SRT Hellcat", "SRT Hellcat Redeye"],
    "Durango": ["SXT", "GT", "Citadel", "R/T", "SRT Hellcat"],
    "Hornet": ["GT", "R/T", "R/T Plus"],
    "Journey": ["SE", "SXT", "Crossroad", "GT"],
    "Grand Caravan": ["SE", "SXT", "GT", "R/T", "Crew"],
    "Dart": ["SE", "SXT", "Rallye", "Limited", "GT"],
    "Avenger": ["SE", "SXT", "R/T"],
    "Caliber": ["SE", "SXT", "R/T", "SRT4"],
    "Nitro": ["SE", "SXT", "R/T"],
    "Viper": ["SRT", "GT", "ACR", "GTS"]
  },
  "Ford": {
    "Bronco": ["Base", "Big Bend", "Black Diamond", "Outer Banks", "Badlands", "Wildtrak", "Raptor"],
    "Bronco Sport": ["Base", "Big Bend", "Outer Banks", "Badlands"],
    "Edge": ["SE", "SEL", "ST-Line", "ST", "Titanium"],
    "Escape": ["Base", "Active", "ST-Line", "ST-Line Select", "Platinum"],
    "Expedition": ["XLT", "Limited", "Timberline", "King Ranch", "Platinum"],
    "Explorer": ["Base", "XLT", "ST-Line", "Limited", "Timberline", "ST", "Platinum"],
    "F-150": ["XL", "STX", "XLT", "Lariat", "King Ranch", "Platinum", "Limited", "Tremor", "Raptor"],
    "F-250": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited"],
    "F-350": ["XL", "XLT", "Lariat", "King Ranch", "Platinum", "Limited"],
    "Maverick": ["XL", "XLT", "Lariat", "Tremor"],
    "Mustang": ["EcoBoost", "EcoBoost Premium", "GT", "GT Premium", "Dark Horse", "Mach 1"],
    "Mustang Mach-E": ["Select", "Premium", "California Route 1", "GT"],
    "Ranger": ["XL", "XLT", "Lariat", "Raptor"],
    "Lightning": ["Pro", "XLT", "Lariat", "Platinum"],
    "Transit": ["Base", "XL", "XLT"],
    "Transit Connect": ["XL", "XLT"],
    "Fusion": ["S", "SE", "SEL", "Titanium", "Sport", "Energi SE", "Energi Titanium"],
    "Focus": ["S", "SE", "SEL", "Titanium", "ST", "RS"],
    "Fiesta": ["S", "SE", "Titanium", "ST"],
    "Taurus": ["SE", "SEL", "Limited", "SHO"],
    "Flex": ["SE", "SEL", "Limited"],
    "C-Max": ["SE", "SEL", "Energi"],
    "E-Series": ["E-150", "E-250", "E-350"],
    "EcoSport": ["S", "SE", "SES", "Titanium"],
    "Five Hundred": ["SE", "SEL", "Limited"],
    "Freestar": ["Base", "SE", "SES", "SEL", "Limited"],
    "Freestyle": ["SE", "SEL", "Limited"],
    "Excursion": ["XLS", "XLT", "Eddie Bauer", "Limited"]
  },
  "Genesis": {
    "G70": ["2.0T Standard", "2.0T Advanced", "3.3T Sport Advanced", "3.3T Sport Prestige"],
    "G80": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "Sport"],
    "G90": ["3.5T Standard", "3.5T Prestige", "e3.5T"],
    "GV60": ["Standard", "Advanced", "Performance"],
    "GV70": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "3.5T Sport Advanced", "3.5T Sport Prestige"],
    "GV80": ["2.5T Standard", "2.5T Advanced", "2.5T Prestige", "3.5T Advanced", "3.5T Prestige"],
    "GV80 Coupe": ["2.5T Standard", "2.5T Advanced", "3.5T Sport Prestige"],
    "Electrified G80": ["Standard", "Advanced", "Prestige"],
    "Electrified GV70": ["Standard", "Advanced", "Prestige"]
  },
  "GMC": {
    "Acadia": ["SLE", "SLT", "AT4", "Denali"],
    "Canyon": ["Elevation", "AT4", "AT4X", "Denali"],
    "Sierra 1500": ["Pro", "SLE", "Elevation", "SLT", "AT4", "AT4X", "Denali", "Denali Ultimate"],
    "Sierra 2500HD": ["Pro", "SLE", "SLT", "AT4", "AT4X", "Denali", "Denali Ultimate"],
    "Sierra 3500HD": ["Pro", "SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Terrain": ["SLE", "SLT", "AT4", "Denali"],
    "Yukon": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Yukon XL": ["SLE", "SLT", "AT4", "Denali", "Denali Ultimate"],
    "Hummer EV": ["EV2", "EV2X", "EV3X", "Edition 1"],
    "Envoy": ["SLE", "SLT", "Denali"],
    "Savana": ["1500 LS", "2500 LS", "3500 LS"]
  },
  "Honda": {
    "Accord": ["LX", "EX", "EX-L", "Sport", "Sport SE", "Touring"],
    "Civic": ["LX", "Sport", "EX", "EX-L", "Touring", "Si", "Type R"],
    "CR-V": ["LX", "EX", "EX-L", "Sport", "Sport Touring"],
    "HR-V": ["LX", "Sport", "EX-L"],
    "Odyssey": ["LX", "EX", "EX-L", "Touring", "Elite"],
    "Passport": ["EX-L", "Sport", "TrailSport", "Touring", "Elite"],
    "Pilot": ["LX", "EX", "EX-L", "Sport", "TrailSport", "Touring", "Elite"],
    "Ridgeline": ["Sport", "RTL", "RTL-E", "TrailSport", "Black Edition"],
    "Fit": ["LX", "Sport", "EX", "EX-L"],
    "Prologue": ["EX", "Touring"],
    "Insight": ["LX", "EX", "Touring"],
    "Element": ["LX", "EX", "EX-P", "SC"],
    "Crosstour": ["EX", "EX-L", "EX-L V6"],
    "Clarity": ["Base", "Touring"],
    "S2000": ["Base"],
    "CR-Z": ["Base", "EX"]
  },
  "Hyundai": {
    "Elantra": ["SE", "SEL", "Limited", "N Line", "N"],
    "Ioniq 5": ["SE Standard Range", "SE", "SEL", "Limited"],
    "Ioniq 6": ["SE Standard Range", "SE", "SEL", "Limited"],
    "Kona": ["SE", "SEL", "N Line", "Limited", "N"],
    "Kona Electric": ["SE", "SEL", "Limited"],
    "Palisade": ["SE", "SEL", "XRT", "Limited", "Calligraphy"],
    "Santa Cruz": ["SE", "SEL", "SEL Activity", "Limited"],
    "Santa Fe": ["SE", "SEL", "XRT", "Limited", "Calligraphy"],
    "Sonata": ["SE", "SEL", "SEL Plus", "Limited", "N Line"],
    "Tucson": ["SE", "SEL", "XRT", "N Line", "Limited"],
    "Venue": ["SE", "SEL"],
    "Accent": ["SE", "SEL", "Limited"],
    "Veloster": ["2.0", "2.0 Premium", "Turbo", "Turbo R-Spec", "Turbo Ultimate", "N"],
    "Azera": ["Base", "Limited"],
    "Genesis Coupe": ["2.0T", "2.0T Premium", "2.0T R-Spec", "3.8", "3.8 Grand Touring", "3.8 Ultimate"],
    "Genesis Sedan": ["3.8", "3.8 Technology", "5.0", "5.0 Ultimate"],
    "Entourage": ["GLS", "SE", "Limited"],
    "Veracruz": ["GLS", "SE", "Limited"],
    "Tiburon": ["GS", "GT", "SE"],
    "Nexo": ["Blue", "Limited"],
    "Ioniq": ["Blue", "SE", "SEL", "Limited", "Plug-in Hybrid"],
    "Santa Fe XL": ["SE", "Limited", "Ultimate"],
    "Tucson Hybrid": ["Blue", "SEL", "Limited"],
    "Santa Fe Hybrid": ["Blue", "SEL", "Limited"],
    "Elantra Hybrid": ["Blue", "SEL", "Limited"],
    "Sonata Hybrid": ["Blue", "SEL", "Limited"]
  },
  "Infiniti": {
    "Q50": ["Pure", "Luxe", "Sensory", "Red Sport 400"],
    "Q60": ["Pure", "Luxe", "Red Sport 400"],
    "QX50": ["Pure", "Luxe", "Essential", "Sensory", "Autograph"],
    "QX55": ["Luxe", "Essential", "Sensory"],
    "QX60": ["Pure", "Luxe", "Sensory", "Autograph"],
    "QX80": ["Luxe", "Sensory", "Autograph"],
    "Q40": ["Base", "Premium", "Sport"],
    "Q70": ["3.7", "5.6", "3.7 Sport", "5.6 Sport", "Hybrid"],
    "QX30": ["Base", "Premium", "Sport", "Essential"],
    "QX70": ["Base", "Premium", "Sport"],
    "G35": ["Base", "Sport", "x"],
    "G37": ["Base", "Journey", "x", "Sport", "IPL"],
    "M35": ["Base", "x", "Sport"],
    "M37": ["Base", "x", "Sport"],
    "M45": ["Base", "Sport"],
    "M56": ["Base", "x", "Sport"],
    "FX35": ["Base", "Sport"],
    "FX45": ["Base", "Sport"],
    "FX50": ["Base", "Sport"],
    "JX35": ["Base"],
    "EX35": ["Base", "Journey"],
    "EX37": ["Base", "Journey"]
  },
  "Jeep": {
    "Cherokee": ["Latitude", "Latitude Lux", "Altitude", "Limited", "Trailhawk"],
    "Compass": ["Sport", "Latitude", "Altitude", "Limited", "Trailhawk"],
    "Gladiator": ["Sport", "Willys", "Overland", "Rubicon", "Mojave"],
    "Grand Cherokee": ["Laredo", "Altitude", "Limited", "Overland", "Trailhawk", "Summit", "Summit Reserve"],
    "Grand Cherokee L": ["Laredo", "Altitude", "Limited", "Overland", "Summit", "Summit Reserve"],
    "Grand Wagoneer": ["Series I", "Series II", "Series III", "Obsidian"],
    "Renegade": ["Sport", "Latitude", "Altitude", "Limited", "Trailhawk"],
    "Wagoneer": ["Series I", "Series II", "Series III"],
    "Wrangler": ["Sport", "Sport S", "Willys", "Sahara", "Rubicon"],
    "Liberty": ["Sport", "Limited", "Renegade", "Jet"],
    "Patriot": ["Sport", "Latitude", "Limited", "High Altitude"],
    "Commander": ["Sport", "Limited", "Overland"],
    "Grand Cherokee WK": ["Laredo", "Limited", "Overland", "SRT8"]
  },
  "Kia": {
    "EV6": ["Light", "Wind", "GT-Line", "GT"],
    "EV9": ["Light", "Wind", "GT-Line"],
    "Forte": ["LXS", "GT-Line", "GT"],
    "K5": ["LXS", "GT-Line", "EX", "GT"],
    "Seltos": ["LX", "S", "EX", "SX", "SX Turbo"],
    "Sorento": ["LX", "S", "EX", "SX", "SX Prestige", "X-Line", "X-Pro"],
    "Soul": ["LX", "S", "EX", "Turbo"],
    "Sportage": ["LX", "EX", "X-Line", "SX", "SX Prestige", "X-Pro", "X-Pro Prestige"],
    "Telluride": ["LX", "S", "EX", "SX", "SX Prestige", "X-Line", "X-Pro"],
    "Carnival": ["LX", "EX", "SX", "SX Prestige"],
    "Optima": ["LX", "LX Turbo", "S", "EX", "SX", "SX Turbo", "SXL"],
    "Rio": ["LX", "S", "EX", "SX"],
    "Cadenza": ["Base", "Premium", "Technology", "Limited"],
    "Stinger": ["GT-Line", "GT1", "GT2"],
    "Niro": ["LX", "LXS", "EX", "EX Premium", "SX Touring"],
    "Niro EV": ["Wind", "Wave"],
    "Sedona": ["L", "LX", "EX", "SX", "SXL"],
    "Sportage Hybrid": ["LX", "EX", "SX Prestige"],
    "Sorento Hybrid": ["LX", "EX", "SX Prestige"],
    "K900": ["Luxury", "Premium"],
    "Amanti": ["Base"],
    "Borrego": ["LX", "EX", "EX V8"],
    "Rondo": ["LX", "EX"],
    "Spectra": ["LX", "EX", "SX"],
    "Soul EV": ["Base", "Plus"]
  },
  "Lexus": {
    "ES 250": ["Base", "Luxury", "Ultra Luxury"],
    "ES 300h": ["Base", "Luxury", "Ultra Luxury"],
    "ES 350": ["Base", "Luxury", "F Sport", "Ultra Luxury"],
    "GS 300": ["Base", "F Sport"],
    "GS 350": ["Base", "F Sport"],
    "GS 430": ["Base"],
    "GS 450h": ["Base", "F Sport"],
    "GS 460": ["Base"],
    "GS F": ["Base"],
    "GX 460": ["Base", "Luxury", "Premium"],
    "GX 470": ["Base"],
    "GX 550": ["Premium", "Premium Plus", "Luxury", "Overtrail", "Overtrail+"],
    "IS 200t": ["Base", "F Sport"],
    "IS 250": ["Base", "F Sport"],
    "IS 300": ["Base", "F Sport"],
    "IS 350": ["Base", "F Sport"],
    "IS 500": ["F Sport Performance", "F Sport Performance Premium"],
    "IS F": ["Base"],
    "LC 500": ["Base", "Touring", "Inspiration Series"],
    "LC 500h": ["Base", "Touring"],
    "LS 400": ["Base"],
    "LS 430": ["Base"],
    "LS 460": ["Base", "L"],
    "LS 500": ["Base", "F Sport", "Luxury"],
    "LS 500h": ["Base", "F Sport", "Luxury"],
    "LS 600h": ["Base", "L"],
    "LX 470": ["Base"],
    "LX 570": ["Base"],
    "LX 600": ["Base", "Premium", "Luxury", "F Sport", "Ultra Luxury"],
    "NX 200t": ["Base", "F Sport"],
    "NX 250": ["Base", "Premium", "Luxury"],
    "NX 300": ["Base", "F Sport", "Luxury"],
    "NX 300h": ["Base", "Luxury"],
    "NX 350": ["F Sport"],
    "NX 350h": ["Base", "Premium", "Luxury", "F Sport"],
    "NX 450h+": ["Base", "Premium", "Luxury", "F Sport"],
    "RC 300": ["Base", "F Sport"],
    "RC 350": ["Base", "F Sport"],
    "RC F": ["Base", "Fuji Speedway Edition"],
    "RX 300": ["Base"],
    "RX 330": ["Base"],
    "RX 350": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 350h": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 400h": ["Base"],
    "RX 450h": ["Base", "Premium", "Luxury", "F Sport"],
    "RX 450h+": ["Base", "Premium", "Luxury"],
    "RX 500h": ["F Sport Performance"],
    "TX 350": ["Base", "Premium", "Luxury"],
    "TX 500h": ["F Sport", "Premium", "Luxury"],
    "TX 550h+": ["Base", "Premium", "Luxury"],
    "UX 200": ["Base", "Premium", "Luxury", "F Sport"],
    "UX 250h": ["Base", "Premium", "Luxury", "F Sport"],
    "RZ 300e": ["Base", "Premium"],
    "RZ 450e": ["Base", "Premium"],
    "CT 200h": ["Base", "Premium", "F Sport"],
    "HS 250h": ["Base", "Premium"],
    "SC 430": ["Base"],
    "LFA": ["Base"]
  },
  "Lincoln": {
    "Aviator": ["Standard", "Reserve"],
    "Corsair": ["Standard", "Reserve"],
    "Nautilus": ["Standard", "Reserve"],
    "Navigator": ["Standard", "Reserve", "Black Label"],
    "Navigator L": ["Standard", "Reserve", "Black Label"],
    "MKC": ["Premiere", "Select", "Reserve", "Black Label"],
    "MKX": ["Premiere", "Select", "Reserve", "Black Label"],
    "MKZ": ["Premiere", "Select", "Reserve", "Black Label"],
    "MKS": ["Base", "EcoBoost"],
    "MKT": ["Base", "EcoBoost"],
    "Town Car": ["Signature", "Executive", "Cartier"],
    "Continental": ["Premiere", "Select", "Reserve", "Black Label"],
    "LS": ["V6", "V8"]
  },
  "Mazda": {
    "CX-5": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "S Premium Plus", "Turbo"],
    "CX-30": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "Turbo", "Turbo Premium Plus"],
    "CX-50": ["S", "S Select", "S Preferred", "S Preferred Plus", "S Premium", "S Premium Plus", "Turbo", "Turbo Premium Plus", "Turbo Meridian"],
    "CX-70": ["S Premium", "S Premium Plus", "Turbo Premium", "Turbo Premium Plus"],
    "CX-90": ["S", "S Select", "S Preferred", "S Preferred Plus", "S Premium", "S Premium Plus", "Turbo S", "Turbo S Premium", "Turbo S Premium Plus"],
    "Mazda3": ["S", "S Select", "S Preferred", "S Carbon Edition", "S Premium", "Turbo", "Turbo Premium Plus"],
    "MX-5 Miata": ["Sport", "Club", "Grand Touring"],
    "CX-9": ["Sport", "Touring", "Carbon Edition", "Grand Touring", "Signature"],
    "Mazda6": ["Sport", "Touring", "Grand Touring", "Grand Touring Reserve", "Signature", "Carbon Edition"],
    "CX-3": ["Sport", "Touring", "Grand Touring"],
    "CX-7": ["Sport", "Grand Touring"],
    "Mazda5": ["Sport", "Touring", "Grand Touring"],
    "Mazda2": ["Sport", "Touring"],
    "RX-8": ["Sport", "Grand Touring", "R3"],
    "MX-5 Miata RF": ["Club", "Grand Touring"],
    "Tribute": ["i", "s"],
    "CX-50 Hybrid": ["S Preferred", "S Premium", "Turbo Premium Plus"]
  },
  "Mercedes-Benz": {
    "A 220": ["Base", "AMG Line"],
    "C 300": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "C 43 AMG": ["Base"],
    "C 63 AMG": ["Base", "S"],
    "CLA 250": ["Base", "AMG Line"],
    "CLE 300": ["Base", "AMG Line"],
    "CLE 450": ["Base", "AMG Line"],
    "E 300": ["Base", "Luxury", "Sport"],
    "E 350": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "E 450": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "E 53 AMG": ["Base"],
    "E 63 AMG": ["Base", "S"],
    "S 500": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "S 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "S 63 AMG": ["Base"],
    "GLA 250": ["Base", "AMG Line"],
    "GLB 250": ["Base", "AMG Line"],
    "GLC 300": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLC 43 AMG": ["Base"],
    "GLC 63 AMG": ["Base", "S"],
    "GLE 350": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLE 450": ["Base", "AMG Line"],
    "GLE 53 AMG": ["Base"],
    "GLE 63 AMG": ["Base", "S"],
    "GLS 450": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLS 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "GLS 63 AMG": ["Base"],
    "G 550": ["Base", "AMG Line"],
    "G 63 AMG": ["Base"],
    "EQS 450+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQS 580": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQE 350+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "AMG GT": ["Base", "43", "53", "55", "63"],
    "AMG GT 63": ["Base", "S"],
    "B 250e": ["Base"],
    "CLA 45 AMG": ["Base"],
    "GLA 35 AMG": ["Base"],
    "GLA 45 AMG": ["Base"],
    "GLK 250": ["Base"],
    "GLK 350": ["Base"],
    "ML 350": ["Base", "BlueTEC"],
    "ML 550": ["Base"],
    "ML 63 AMG": ["Base"],
    "GL 450": ["Base"],
    "GL 550": ["Base"],
    "GL 63 AMG": ["Base"],
    "R 350": ["Base", "BlueTEC"],
    "SL 450": ["Base", "AMG Line"],
    "SL 550": ["Base"],
    "SL 55 AMG": ["Base"],
    "SL 63 AMG": ["Base"],
    "SLK 250": ["Base"],
    "SLK 350": ["Base"],
    "SLK 55 AMG": ["Base"],
    "SLC 300": ["Base"],
    "SLC 43 AMG": ["Base"],
    "Metris": ["Base", "Worker"],
    "Sprinter": ["1500", "2500", "3500"],
    "EQB 250+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQB 350": ["Base", "AMG Line"],
    "EQS SUV 450+": ["Base", "Exclusive", "AMG Line", "Pinnacle"],
    "EQE SUV 350+": ["Base", "Exclusive", "AMG Line", "Pinnacle"]
  },
  "Nissan": {
    "Altima": ["S", "SV", "SR", "SL", "Platinum"],
    "Armada": ["S", "SV", "SL", "Platinum", "Midnight Edition"],
    "Frontier": ["S", "SV", "Pro-X", "Pro-4X"],
    "Kicks": ["S", "SV", "SR"],
    "Leaf": ["S", "SV", "SV Plus", "SL Plus"],
    "Maxima": ["SV", "SR", "Platinum"],
    "Murano": ["S", "SV", "SL", "Platinum"],
    "Pathfinder": ["S", "SV", "SL", "Rock Creek", "Platinum"],
    "Rogue": ["S", "SV", "SL", "Platinum"],
    "Rogue Sport": ["S", "SV", "SL"],
    "Sentra": ["S", "SV", "SR"],
    "Titan": ["S", "SV", "Pro-4X", "SL", "Platinum Reserve"],
    "Titan XD": ["S", "SV", "Pro-4X", "SL", "Platinum Reserve"],
    "Versa": ["S", "SV", "SR"],
    "Versa Note": ["S", "S Plus", "SV", "SR", "SL"],
    "Z": ["Sport", "Performance"],
    "370Z": ["Base", "Sport", "Touring", "Sport Touring", "NISMO"],
    "350Z": ["Base", "Enthusiast", "Touring", "Track", "Grand Touring", "NISMO"],
    "Ariya": ["Engage", "Venture+", "Evolve+", "Empower+", "Platinum+"],
    "GT-R": ["Premium", "Track Edition", "NISMO"],
    "Juke": ["S", "SV", "SL", "NISMO", "NISMO RS"],
    "Quest": ["S", "SV", "SL", "Platinum"],
    "Cube": ["1.8 Base", "1.8 S", "1.8 SL"],
    "Xterra": ["S", "X", "Pro-4X"],
    "NV200": ["S", "SV"],
    "NV Cargo": ["1500 S", "2500 S", "3500 S", "SV", "SL"],
    "NV Passenger": ["3500 S", "SV", "SL"]
  },
  "Porsche": {
    "911": ["Carrera", "Carrera S", "Carrera T", "Carrera GTS", "Turbo", "Turbo S", "GT3", "GT3 RS"],
    "Cayenne": ["Base", "E-Hybrid", "S", "GTS", "Turbo", "Turbo GT"],
    "Cayenne Coupe": ["Base", "E-Hybrid", "S", "GTS", "Turbo", "Turbo GT"],
    "Macan": ["Base", "S", "GTS", "T", "Turbo"],
    "Panamera": ["Base", "4", "4S", "GTS", "4S E-Hybrid", "Turbo", "Turbo S"],
    "Taycan": ["Base", "4S", "GTS", "Turbo", "Turbo S"],
    "Taycan Cross Turismo": ["4", "4S", "GTS", "Turbo", "Turbo S"],
    "718 Boxster": ["Base", "T", "S", "GTS 4.0", "Spyder"],
    "718 Cayman": ["Base", "T", "S", "GTS 4.0", "GT4", "GT4 RS"]
  },
  "Ram": {
    "1500": ["Tradesman", "Big Horn", "Laramie", "Rebel", "Limited", "Limited Longhorn", "TRX"],
    "1500 Classic": ["Tradesman", "Express", "Big Horn", "Lone Star"],
    "2500": ["Tradesman", "Big Horn", "Laramie", "Power Wagon", "Limited", "Limited Longhorn"],
    "3500": ["Tradesman", "Big Horn", "Laramie", "Limited", "Limited Longhorn"],
    "ProMaster": ["1500 Low Roof", "1500 High Roof", "2500 High Roof", "3500 High Roof"],
    "ProMaster City": ["Tradesman", "SLT"],
    "1500 REV": ["Tradesman", "Big Horn", "Laramie", "Limited"]
  },
  "Subaru": {
    "Ascent": ["Base", "Premium", "Onyx Edition", "Limited", "Touring"],
    "Crosstrek": ["Base", "Premium", "Sport", "Limited"],
    "Forester": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Impreza": ["Base", "Premium", "Sport", "Limited"],
    "Legacy": ["Base", "Premium", "Sport", "Limited", "Touring"],
    "Outback": ["Base", "Premium", "Onyx Edition", "Limited", "Touring", "Wilderness", "Onyx Edition XT", "Limited XT", "Touring XT"],
    "Solterra": ["Premium", "Limited", "Touring"],
    "WRX": ["Base", "Premium", "Limited", "GT"],
    "BRZ": ["Premium", "Limited"],
    "STI": ["Base", "Limited"],
    "Tribeca": ["Base", "Premium", "Limited", "Touring"],
    "Baja": ["Sport", "Turbo"],
    "SVX": ["Base", "LSi"],
    "Forester Wilderness": ["Base"]
  },
  "Tesla": {
    "Model 3": ["Base", "Long Range", "Performance"],
    "Model S": ["Base", "Plaid"],
    "Model X": ["Base", "Plaid"],
    "Model Y": ["Base", "Long Range", "Performance"],
    "Cybertruck": ["Rear-Wheel Drive", "All-Wheel Drive", "Cyberbeast", "Foundation Series"]
  },
  "Toyota": {
    "4Runner": ["SR5", "SR5 Premium", "TRD Sport", "TRD Off-Road", "TRD Off-Road Premium", "Limited", "TRD Pro"],
    "86/GR86": ["Base", "Premium"],
    "Camry": ["LE", "SE", "XLE", "XSE", "TRD"],
    "Corolla": ["L", "LE", "SE", "XLE", "XSE"],
    "Corolla Cross": ["L", "LE", "XLE", "SE"],
    "Corolla Hatchback": ["SE", "XSE"],
    "Grand Highlander": ["LE", "XLE", "Limited", "Platinum"],
    "Highlander": ["L", "LE", "XLE", "XSE", "Limited", "Platinum"],
    "Land Cruiser": ["Base", "1958", "First Edition"],
    "Prius": ["LE", "XLE", "Limited", "Prime SE", "Prime XSE"],
    "RAV4": ["LE", "XLE", "XLE Premium", "SE", "XSE", "Adventure", "TRD Off-Road", "Limited", "Prime SE", "Prime XSE"],
    "Sequoia": ["SR5", "Limited", "Platinum", "TRD Pro", "Capstone"],
    "Sienna": ["LE", "XLE", "XSE", "Limited", "Platinum"],
    "Tacoma": ["SR", "SR5", "TRD Sport", "TRD Off-Road", "Limited", "TRD Pro", "Trailhunter"],
    "Tundra": ["SR", "SR5", "Limited", "Platinum", "1794 Edition", "TRD Pro", "Capstone"],
    "Venza": ["LE", "XLE", "Limited"],
    "bZ4X": ["XLE", "Limited"],
    "Crown": ["XLE", "Limited", "Platinum"],
    "Crown Signia": ["XLE", "Limited"],
    "GR Corolla": ["Core", "Circuit Edition", "Morizo Edition", "Premium"],
    "Supra": ["2.0", "3.0", "3.0 Premium", "A91 Edition"],
    "Avalon": ["XLE", "XSE", "Touring", "Limited", "TRD"],
    "Yaris": ["L", "LE", "XLE"],
    "Yaris iA": ["Base"],
    "Matrix": ["Base", "S", "XR", "XRS"],
    "FJ Cruiser": ["Base", "Trail Teams"],
    "C-HR": ["LE", "XLE", "Limited"],
    "Mirai": ["XLE", "Limited"]
  },
  "Volkswagen": {
    "Atlas": ["S", "SE", "SEL", "SEL Premium"],
    "Atlas Cross Sport": ["S", "SE", "SE Technology", "SEL", "SEL Premium"],
    "Golf": ["S", "SE"],
    "Golf GTI": ["S", "SE", "Autobahn"],
    "Golf R": ["Base"],
    "ID.4": ["Standard", "S", "S Plus", "Pro", "Pro S", "Pro S Plus"],
    "ID.Buzz": ["Pro S", "Pro S Plus"],
    "Jetta": ["S", "Sport", "SE", "SEL"],
    "Jetta GLI": ["S", "SE", "Autobahn"],
    "Taos": ["S", "SE", "SEL"],
    "Tiguan": ["S", "SE", "SE R-Line", "SEL", "SEL R-Line"],
    "Arteon": ["SE", "SE R-Line", "SEL R-Line", "SEL Premium R-Line"],
    "Passat": ["S", "SE", "SE Technology", "SEL", "SEL Premium"],
    "CC": ["Sport", "R-Line", "Executive", "V6 Executive"],
    "Beetle": ["S", "SE", "SEL", "Final Edition"],
    "Touareg": ["Sport", "Lux", "Executive", "TDI"],
    "Routan": ["S", "SE", "SEL", "SEL Premium"],
    "Eos": ["Komfort", "Sport", "Lux"],
    "Golf SportWagen": ["S", "SE", "SEL"],
    "Golf Alltrack": ["S", "SE", "SEL"],
    "e-Golf": ["SE", "SEL Premium"]
  },
  "Volvo": {
    "S60": ["Core", "Plus", "Ultimate"],
    "S90": ["Core", "Plus", "Ultimate"],
    "V60": ["Core", "Plus", "Ultimate"],
    "V60 Cross Country": ["Core", "Plus", "Ultimate"],
    "V90": ["Core", "Plus", "Ultimate"],
    "V90 Cross Country": ["Core", "Plus", "Ultimate"],
    "XC40": ["Core", "Plus", "Ultimate"],
    "XC40 Recharge": ["Core", "Plus", "Ultimate"],
    "XC60": ["Core", "Plus", "Ultimate"],
    "XC90": ["Core", "Plus", "Ultimate"],
    "C40 Recharge": ["Core", "Plus", "Ultimate"],
    "EX30": ["Core", "Plus", "Ultra"],
    "EX90": ["Core", "Plus", "Ultra"],
    "S40": ["2.4i", "T5", "T5 AWD"],
    "S80": ["3.2", "T6"],
    "C30": ["T5", "T5 R-Design"],
    "C70": ["T5"],
    "XC70": ["3.2", "T6"]
  },
  "Mitsubishi": {
    "Outlander": ["ES", "SE", "SEL", "GT"],
    "Outlander Sport": ["ES", "SE", "LE", "GT"],
    "Outlander PHEV": ["ES", "SE", "SEL"],
    "Eclipse Cross": ["ES", "SE", "SEL"],
    "Mirage": ["ES", "LE", "SE", "GT"],
    "Mirage G4": ["ES", "LE", "SE", "GT"],
    "Lancer": ["ES", "SE", "GT", "Evolution MR", "Evolution GSR", "Ralliart"],
    "Eclipse": ["GS", "GT", "Spyder GS", "Spyder GT"],
    "Galant": ["ES", "SE", "GT", "Ralliart"],
    "Endeavor": ["LS", "SE", "Limited"],
    "Raider": ["LS", "Duro Cross"],
    "i-MiEV": ["ES"],
    "Montero": ["Limited"],
    "Montero Sport": ["LS", "XLS", "Limited"]
  },
  "Land Rover": {
    "Range Rover": ["SE", "HSE", "Autobiography", "SV Autobiography", "First Edition"],
    "Range Rover Sport": ["SE", "HSE", "HSE Dynamic", "Autobiography", "SVR", "First Edition"],
    "Range Rover Velar": ["S", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE", "First Edition"],
    "Range Rover Evoque": ["S", "SE", "Dynamic SE", "Autobiography"],
    "Defender": ["Base", "S", "SE", "X-Dynamic SE", "X-Dynamic HSE", "X", "V8"],
    "Defender 130": ["SE", "X-Dynamic HSE", "X", "Outbound"],
    "Discovery": ["S", "SE", "R-Dynamic SE", "R-Dynamic HSE", "HSE"],
    "Discovery Sport": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE"],
    "Freelander": ["SE", "HSE"],
    "LR2": ["Base", "HSE"],
    "LR3": ["SE", "HSE"],
    "LR4": ["Base", "HSE", "HSE LUX"]
  },
  "Jaguar": {
    "F-PACE": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE", "R", "SVR"],
    "E-PACE": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE"],
    "I-PACE": ["S", "SE", "HSE", "EV400"],
    "F-TYPE": ["Base", "R-Dynamic", "P450", "R", "R75", "SVR"],
    "XE": ["S", "SE", "R-Dynamic S", "R-Dynamic SE", "R-Dynamic HSE"],
    "XF": ["Premium", "Prestige", "R-Dynamic SE", "R-Dynamic HSE", "S"],
    "XJ": ["XJL Portfolio", "XJL Supercharged", "XJR", "XJR575"],
    "XK": ["Base", "Touring", "XKR", "XKR-S"],
    "S-Type": ["3.0", "4.0", "R"],
    "X-Type": ["2.5", "3.0", "VDP"]
  },
  "Alfa Romeo": {
    "Giulia": ["Base", "Sprint", "Ti", "Ti Sport", "Veloce", "Quadrifoglio"],
    "Stelvio": ["Base", "Sprint", "Ti", "Ti Sport", "Veloce", "Quadrifoglio"],
    "Tonale": ["Sprint", "Ti", "Veloce"],
    "4C": ["Base", "Launch Edition"],
    "4C Spider": ["Base"]
  },
  "Fiat": {
    "500": ["Pop", "Sport", "Lounge", "Abarth"],
    "500e": ["Base", "Inspired By"],
    "500X": ["Pop", "Trekking", "Sport", "Lounge"],
    "500L": ["Pop", "Easy", "Trekking", "Lounge"],
    "500c": ["Pop", "Lounge", "Abarth"],
    "124 Spider": ["Classica", "Lusso", "Abarth"],
    "500 Abarth": ["Base", "Cabrio"]
  },
  "Mini": {
    "Cooper": ["Classic", "S", "Sport"],
    "Cooper S": ["Classic", "Signature", "Iconic"],
    "Cooper Hardtop 2 Door": ["Base", "S", "SE"],
    "Cooper Hardtop 4 Door": ["Base", "S"],
    "Cooper Convertible": ["Base", "S"],
    "Cooper Clubman": ["Base", "S", "JCW"],
    "Cooper Countryman": ["Base", "S", "SE", "JCW"],
    "Cooper Paceman": ["Base", "S", "JCW"],
    "John Cooper Works": ["Hardtop", "Convertible", "Countryman", "Clubman"],
    "Cooper Coupe": ["Base", "S", "JCW"],
    "Cooper Roadster": ["Base", "S", "JCW"]
  },
  "Maserati": {
    "Ghibli": ["Base", "S", "S Q4", "Trofeo", "GranLusso", "GranSport", "Modena", "GT"],
    "Levante": ["Base", "S", "GTS", "Trofeo", "GT", "Modena"],
    "Quattroporte": ["Base", "S", "S Q4", "GTS", "Trofeo", "GT", "Modena"],
    "MC20": ["Base", "Cielo"],
    "GranTurismo": ["Modena", "Trofeo", "Folgore"],
    "Grecale": ["GT", "Modena", "Trofeo", "Folgore"],
    "GranCabrio": ["Modena", "Trofeo", "Folgore"]
  },
  "Rivian": {
    "R1T": ["Explore", "Adventure"],
    "R1S": ["Explore", "Adventure"],
    "R2": ["Base", "Plus"],
    "R3": ["Base", "Plus"]
  },
  "Lucid": {
    "Air": ["Pure", "Touring", "Grand Touring", "Grand Touring Performance", "Sapphire"],
    "Gravity": ["Pure", "Touring", "Grand Touring"]
  },
  "Polestar": {
    "Polestar 2": ["Standard Range Single Motor", "Long Range Single Motor", "Long Range Dual Motor"],
    "Polestar 3": ["Long Range Dual Motor", "Long Range Dual Motor with Performance Pack"],
    "Polestar 4": ["Long Range Single Motor", "Long Range Dual Motor"]
  },
  "smart": {
    "fortwo": ["Pure", "Passion", "Prime", "Proxy"],
    "fortwo Electric Drive": ["Base", "Passion", "Prime"],
    "fortwo Cabrio": ["Passion", "Prime", "Proxy"]
  },
  "Scion": {
    "tC": ["Base", "Release Series"],
    "xB": ["Base", "Release Series"],
    "xD": ["Base", "Release Series"],
    "xA": ["Base"],
    "FR-S": ["Base", "Release Series"],
    "iA": ["Base"],
    "iM": ["Base"],
    "iQ": ["Base"]
  }
};
